Repository sonia-auv/proc_image_processing, pull requests merged in 2021-07, with the labels that each got.

#36 Feature/factory generator workflow
  .github/workflows/docker-image-perception-develop.yml
  .github/workflows/docker-image-perception-feature.yml
  .github/workflows/docker-image-perception-master.yml
  .github/workflows/factory_generator.yml
Labels: Priority: High, Type: Enhancement

#32 Feature/encapsulation
  src/proc_image_processing/algorithm/contour.h
  src/proc_image_processing/algorithm/contour_list.h
  src/proc_image_processing/algorithm/general_function.cc
  src/proc_image_processing/algorithm/general_function.h
  src/proc_image_processing/algorithm/line.h
  src/proc_image_processing/algorithm/major_edge_extractor.h
  src/proc_image_processing/algorithm/moments.h
  src/proc_image_processing/algorithm/object_basic_data.cc
  src/proc_image_processing/algorithm/object_feature_factory.h
  src/proc_image_processing/algorithm/object_ranking_data.h
  src/proc_image_processing/filters/detectors/gate_detector.h
  src/proc_image_processing/filters/detectors/pipe_angle_detector.h
  src/proc_image_processing/filters/detectors/vampire_torpedoes_close_detector.h
  src/proc_image_processing/filters/detectors/vampire_torpedoes_detector.h
  src/proc_image_processing/filters/subtract_plane_adder.h
  src/proc_image_processing/filters/white_filter.h
  src/proc_image_processing/server/target.h
  src/proc_image_processing/server/vision_server.cc
  test/CMakeLists.txt
Labels: Priority: Low, Type: Enhancement

#39 Fix CI tests for CUDA as we can't test these
  .github/workflows/docker-image-perception-develop.yml
  .github/workflows/docker-image-perception-master.yml
Labels: Priority: High

#40 Feature/bugfix path to chainfilters
  config/filterchain/deep_bat_wolf.yaml
  config/filterchain/deep_draugr.yaml
  config/filterchain/deep_front.yaml
  config/filterchain/deep_jiangshi.yaml
  config/filterchain/deep_vampire.yaml
  config/filterchain/deep_vetalas.yaml
  config/filterchain/simple_align_test.yaml
  config/filterchain/simple_bin_handle.yaml
  config/filterchain/simple_body_baby.yaml
  config/filterchain/simple_coffin_handle.yaml
  config/filterchain/simple_jiangshi_backup.yaml
  config/filterchain/simple_pipe45.yaml
  config/filterchain/simple_sonar_vampire.yaml
  config/filterchain/simple_test.yaml
  config/filterchain/simple_test_octogone.yaml
  config/filterchain/simple_vampire_torpille.yaml
  src/proc_image_processing/cpu/config.h
  src/proc_image_processing/cpu/server/detection_task.cc
  src/proc_image_processing/cpu/server/filter_chain.cc
  src/proc_image_processing/cpu/server/filter_chain_manager.cc
  src/proc_image_processing/cpu/server/vision_server.cc
  test/black_box_test.cc
Labels: Priority: High, Type: Bug
